# Generated by Django 4.2 on 2023-11-02 04:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_number",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Not a valid class number", regex="[0-9]{3}"
                            )
                        ],
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_name", models.CharField(max_length=50)),
                (
                    "course_code",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="course-code must have 5 digits",
                                regex="^[0-9]{5}$",
                            )
                        ],
                    ),
                ),
                (
                    "unit_count",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "Select a unit count"),
                            ("Zero", 0),
                            ("One", 1),
                            ("Two", 2),
                            ("Three", 3),
                            ("Four", 4),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "student_number",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="student-number must have 8 digits",
                                regex="^[0-9]{8}$",
                            )
                        ],
                    ),
                ),
                ("enrollment_year", models.DateField()),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "Select a major"),
                            ("CE", "Computer Engineering"),
                            ("CS", "Computer Science"),
                            ("CVE", "Civil Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CME", "Chemical Engineering"),
                            ("AE", "Aerospace Engineering"),
                            ("PHY", "Physics"),
                            ("MATH", "Mathematics"),
                            ("CHEM", "Chemistry"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=7,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="models.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "staff_number",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="staff-number must have 8 digits",
                                regex="^[0-9]{8}$",
                            )
                        ],
                    ),
                ),
                ("hiring_date", models.DateField(blank=True, null=True)),
                (
                    "prof_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Not a valid semester(Winter|Fall|Spring|Summer)",
                                regex="^Winter|Fall|Spring|Summer[0-9]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="models.professor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="offered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="models.professor",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.department",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("deadline", models.DateField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.course",
                    ),
                ),
            ],
        ),
    ]
