# Generated by Django 4.2 on 2023-10-27 15:38

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_course_department_enrollment_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='unit_count',
            field=django_enum.fields.EnumCharField(choices=[('0', 'ZERO'), ('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], max_length=1),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=django_enum.fields.EnumCharField(choices=[('Computer', 'COMPUTER')], max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=django_enum.fields.EnumCharField(choices=[('CE', 'COMPUTER_ENGINEERING'), ('CS', 'COMPUTER_SCIENCE')], max_length=2),
        ),
    ]
